[phases.setup]
nixPkgs = ["playwright-driver.browsers", "gobject-introspection", "nss", "nspr", "dbus", "atk", "cups", "glib", "drm", "at-spi2-atk", "expat", "xorg.libxcb", "xkbcommon", "pango", "cairo", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "mesa", "alsa-lib"]
