COCHES_MAKES = {
    "Abarth": 1,
    "Alfa Romeo": 2,
    "Aston Martin": 3,
    "Audi": 4,
    "Bentley": 5,
    "BMW": 7,
    "Bugatti": 8,
    "Cadillac": 9,
    "Chevrolet": 11,
    "Chrysler": 12,
    "Citroen": 13,
    "Cupra": 121,
    "Dacia": 14,
    "Dodge": 17,
    "Ferrari": 20,
    "Fiat": 21,
    "Ford": 22,
    "Honda": 26,
    "Hyundai": 27,
    "Infiniti": 28,
    "Jaguar": 29,
    "Jeep": 30,
    "Kia": 32,
    "Lamborghini": 34,
    "Land Rover": 36,
    "Lexus": 37,
    "Maserati": 40,
    "Mazda": 41,
    "Mercedes-Benz": 42,
    "Mini": 43,
    "Mitsubishi": 44,
    "Nissan": 45,
    "Opel": 47,
    "Peugeot": 49,
    "Porsche": 50,
    "Renault": 52,
    "Seat": 55,
    "Skoda": 56,
    "Smart": 57,
    "Subaru": 58,
    "Suzuki": 59,
    "Tesla": 120,
    "Toyota": 46,
    "Volkswagen": 63,
    "Volvo": 64,
}

MILANUNCIOS_MAKES = {
    "Audi": 3,
    "BMW": 7,
    "Citroen": 13,
    "Cupra": 121,
    "Dacia": 14,
    "Fiat": 21,
    "Ford": 22,
    "Honda": 26,
    "Hyundai": 27,
    "Jeep": 30,
    "Kia": 32,
    "Land Rover": 36,
    "Lexus": 37,
    "Mazda": 41,
    "Mercedes-Benz": 42,
    "Mini": 43,
    "Mitsubishi": 44,
    "Nissan": 45,
    "Opel": 47,
    "Peugeot": 49,
    "Porsche": 50,
    "Renault": 52,
    "Seat": 55,
    "Skoda": 56,
    "Suzuki": 59,
    "Tesla": 120,
    "Toyota": 46,
    "Volkswagen": 63,
    "Volvo": 64,
}

COCHES_FUEL = {
    "hibrido": 4,
    "electrico": 5,
    "gasolina": 1,
    "diesel": 2,
    "": None,
}
